### ISSUE TITLE
dectection for other datasets

### ISSUE THREAD

**Issue by SleeplessBegonia** [jonasricker/aeroblade#3]
i get the distances of my datasets as distances.csv,i want to know how to use the distances.csc for detection?

**Comment by jonasricker** [comment]
In general, low reconstruction errors (high values in distances.csv, because we take the negative) indicate that an image is generated. For binary detection you need to determine a threshold based on your setting. For instance, you could compute the distances from a reference set of real images and select the threshold that correctly labels 95% of those images as real. This is what we did to compute TPR@5%FPR in Table 3.
